# Generated by Django 3.2.9 on 2021-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
