# Generated by Django 3.2.9 on 2021-11-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('birthplace', models.CharField(blank=True, max_length=250, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
