# Generated by Django 3.2.9 on 2021-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
