# Generated by Django 3.2.9 on 2021-11-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211111_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='books.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
